app:
  paymentgateway:
    url: https://dexter-payment-gateway-dot-hack-mindbenders.an.r.appspot.com/

server:
  port: 8081

spring:
  cloud:
    gcp:
      project-id: dexter-app
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:dexterDatabase
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
