spring:
  cloud:
    gcp:
      project-id: dexter-payment-gateway
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:paymentGateway
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
